# Generated by Django 5.2.3 on 2025-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_to_complete',
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)', verbose_name='Время на выполнение (секунды)'),
            preserve_default=False,
        ),
    ]
