# Generated by Django 5.2.3 on 2025-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_time_to_complete_habit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата Telegram для отправки напоминаний о привычке.', max_length=255, null=True, verbose_name='ID чата Telegram для уведомлений'),
        ),
    ]
