# Generated by Django 5.2.3 on 2025-06-21 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней отправки уведомления'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (секунды)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (в днях)'),
        ),
    ]
