# Generated by Django 5.2.3 on 2025-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_last_notification_sent_alter_habit_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего выполнения'),
        ),
    ]
