# Generated by Django 5.2.3 on 2025-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_last_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)', verbose_name='Время на выполнение (секунды)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность (в днях)'),
        ),
    ]
